package api

import (
	"bytes"
	"context"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"io"
	"net/http"
	"slices"
	"strconv"
	"strings"

	"github.com/danielgtaylor/huma/v2"
	"go.kenn.io/msgvault/internal/store"
)

const (
	// These mirror the store's clamping. Duplicating them is deliberate: the
	// response echoes the effective page size, and a bounded result is an
	// endpoint contract rather than a store implementation detail.
	identityMatchDefaultLimit = 100
	identityMatchMaxLimit     = 500
)

// IdentityMatchStore is the feature-local capability for reviewable identity
// match candidates.
type IdentityMatchStore interface {
	ListIdentityMatchCandidatesContext(
		ctx context.Context, states []store.IdentityMatchState, limit, offset int,
	) ([]store.IdentityMatchCandidate, error)
	ListContactMatchCandidatesContext(
		ctx context.Context, states []store.IdentityMatchState, limit, offset int,
	) ([]store.IdentityMatchCandidate, error)
	ListPersonDuplicateCandidatesContext(
		ctx context.Context, states []store.IdentityMatchState, limit, offset int,
	) ([]store.IdentityMatchCandidate, error)
	DescribeIdentityMatchCandidatesContext(
		ctx context.Context, candidates []store.IdentityMatchCandidate,
	) ([]store.IdentityMatchEndpointSummary, []store.ContactMatchStatus, error)
	GetIdentityMatchCandidateContext(
		ctx context.Context, candidateID int64,
	) (*store.IdentityMatchCandidate, error)
	AcceptIdentityMatchCandidateContext(
		ctx context.Context, candidateID int64, decidedBy string, notes *string,
	) (*store.IdentityMatchCandidate, int64, error)
	DecideIdentityMatchCandidateContext(
		ctx context.Context, candidateID int64, state store.IdentityMatchState,
		decidedBy string, notes *string,
	) (*store.IdentityMatchCandidate, error)
	IdentityRevision() (int64, error)
}

// ContactMatchBuilder refreshes contact-match candidates on demand.
type ContactMatchBuilder interface {
	BuildContactMatchCandidatesContext(ctx context.Context) (*store.ContactMatchBuildResult, error)
}

// IdentityMatchCandidatesResponse is a bounded page of candidates with their
// evidence. Endpoints resolves every candidate endpoint on the page to a name
// and addresses; ContactMatches carries the live bind/merge verdict of each
// participant-to-person candidate on the page.
type IdentityMatchCandidatesResponse struct {
	Candidates     []store.IdentityMatchCandidate       `json:"candidates"`
	Endpoints      []store.IdentityMatchEndpointSummary `json:"endpoints"`
	ContactMatches []store.ContactMatchStatus           `json:"contact_matches"`
	Limit          int                                  `json:"limit"`
	Offset         int                                  `json:"offset"`
}

// identityMatchOriginContactMatch selects candidates generated by matching
// contact-only profiles against archive participants.
const identityMatchOriginContactMatch = "contact_match"

// identityMatchOriginPersonDuplicate selects participant pairs the
// duplicate people judgment proposed as possibly one person.
const identityMatchOriginPersonDuplicate = "person_duplicate"

var identityMatchOrigins = []string{identityMatchOriginContactMatch, identityMatchOriginPersonDuplicate}

// DecideIdentityMatchRequest is the optional body of an accept or reject.
type DecideIdentityMatchRequest struct {
	Notes *string `json:"notes,omitzero" nullable:"false"`
}

// IdentityMatchAcceptResponse reports the decided candidate, identity revision,
// and synchronous analytics-cache state. The link is durable even when the
// cache is stale.
type IdentityMatchAcceptResponse struct {
	Candidate        store.IdentityMatchCandidate `json:"candidate"`
	IdentityRevision int64                        `json:"identity_revision"`
	CacheState       string                       `json:"cache_state" enum:"ready,stale"`
}

// IdentityMatchRejectResponse reports the retained rejected candidate, the
// post-mutation identity revision, and the synchronous cache state. A
// rejection of an earlier system acceptance can remove an owned direct edge;
// in that case the revision and cache state have the same contract as accept.
type IdentityMatchRejectResponse struct {
	Candidate        store.IdentityMatchCandidate `json:"candidate"`
	IdentityRevision int64                        `json:"identity_revision"`
	CacheState       string                       `json:"cache_state" enum:"ready,stale"`
}

func (s *Server) registerIdentityMatchRoutes(api huma.API) {
	list := rawAPIV1Operation("listIdentityMatchCandidates", http.MethodGet,
		"/identity/match-candidates", "List reviewable identity match candidates")
	list.Description = "Candidates are evidence-backed suggestions, never applied links. " +
		"Only a repeated stable provider or Beeper user ID, or two addresses that deliver " +
		"to the same mailbox (basis email_equivalence), is confirmed automatically; a " +
		"username, phone, email, dot-only address variant (email_dot_variant), display " +
		"name, or shared conversation is evidence and waits for an explicit decision."
	list.Responses = jsonResponsesFor[IdentityMatchCandidatesResponse](api)
	addErrorResponses(api, list.Responses, http.StatusServiceUnavailable)
	registerRawHumaRoute(api, list, s.handleListIdentityMatchCandidates)

	accept := rawAPIV1Operation("acceptIdentityMatchCandidate", http.MethodPost,
		"/identity/match-candidates/{id}/accept", "Accept an identity match candidate")
	accept.Description = "Accepting is the explicit user confirmation the matching policy " +
		"requires. A participant pair is linked through the normal identity link path, so " +
		"a match spanning two curated people is refused rather than merged. A " +
		"participant-to-person match whose participant cluster has no person promotes the " +
		"cluster and merges it into that person, which survives; when the cluster already " +
		"belongs to another person, the 409 names both profiles so the user can choose the " +
		"survivor of an explicit merge."
	accept.RequestBody = jsonRequestBodyFor[DecideIdentityMatchRequest](api)
	accept.RequestBody.Required = false
	accept.Responses = jsonResponsesFor[IdentityMatchAcceptResponse](api)
	addErrorResponses(api, accept.Responses, http.StatusConflict, http.StatusNotFound,
		http.StatusServiceUnavailable)
	accept.Responses[httpStatusKey(http.StatusConflict)] = personMergeConflictResponseFor(api)
	registerRawHumaRoute(api, accept, s.handleAcceptIdentityMatchCandidate)

	reject := rawAPIV1Operation("rejectIdentityMatchCandidate", http.MethodPost,
		"/identity/match-candidates/{id}/reject", "Reject an identity match candidate")
	reject.Description = "A rejected suggestion is retained rather than deleted, so the same " +
		"low-quality inference is not proposed again on the next import."
	reject.RequestBody = jsonRequestBodyFor[DecideIdentityMatchRequest](api)
	reject.RequestBody.Required = false
	reject.Responses = jsonResponsesFor[IdentityMatchRejectResponse](api)
	addErrorResponses(api, reject.Responses, http.StatusConflict, http.StatusNotFound,
		http.StatusServiceUnavailable)
	registerRawHumaRoute(api, reject, s.handleRejectIdentityMatchCandidate)

	build := rawAPIV1Operation("buildContactMatchCandidates", http.MethodPost,
		"/identity/contact-matches/build", "Refresh contact-match candidates")
	build.Description = "Matches the exact email and phone contact points of profiles with no " +
		"archive identity (for example, imported contacts) against archive participants and " +
		"writes one reviewable candidate per matched identity cluster. Refreshing is " +
		"idempotent and never accepts a match."
	build.Responses = jsonResponsesFor[store.ContactMatchBuildResult](api)
	addErrorResponses(api, build.Responses, http.StatusServiceUnavailable)
	registerRawHumaRoute(api, build, s.handleBuildContactMatchCandidates)

	equivalence := rawAPIV1Operation("linkEquivalentEmailAddresses", http.MethodPost,
		"/identity/email-equivalence/link", "Link email addresses that share a mailbox")
	equivalence.Description = "Links participants whose addresses deliver to the same " +
		"mailbox: anything after a plus sign is ignored on every domain, and Gmail also " +
		"ignores dots and treats googlemail.com as gmail.com. Each link is an ordinary " +
		"participant link owned by an accepted email_equivalence candidate, so unlinking " +
		"undoes it for good. Addresses on two different people, and non-Gmail addresses " +
		"that differ only by dots, become reviewable candidates instead. Relay and robot " +
		"mailboxes (reply+<token>@, bounces+<id>@), identities that are not a person, and " +
		"addresses detached from a person are never linked. The daemon runs " +
		"the same pass after each successful import; this endpoint scans the whole " +
		"archive even when nothing is new. Repeating it is safe."
	equivalence.Responses = jsonResponsesFor[store.EmailEquivalenceResult](api)
	addErrorResponses(api, equivalence.Responses, http.StatusServiceUnavailable)
	registerRawHumaRoute(api, equivalence, s.handleLinkEquivalentEmailAddresses)
}

// EmailEquivalenceLinker links participants whose addresses share a mailbox.
type EmailEquivalenceLinker interface {
	LinkEquivalentEmailAddressesContext(
		ctx context.Context, force bool,
	) (*store.EmailEquivalenceResult, error)
}

func (s *Server) handleLinkEquivalentEmailAddresses(w http.ResponseWriter, r *http.Request) {
	linker, ok := s.store.(EmailEquivalenceLinker)
	if !ok {
		writeError(w, http.StatusServiceUnavailable, "identity_matches_unavailable",
			"Identity match review is unavailable")
		return
	}
	result, err := linker.LinkEquivalentEmailAddressesContext(r.Context(), true)
	if err != nil {
		s.writeIdentityMatchError(w, err)
		return
	}
	if result.Linked > 0 {
		// New links change identity clusters, so refresh the identity
		// datasets like every other identity mutation endpoint.
		result.CacheState = s.refreshIdentityCacheState(r.Context())
	}
	w.Header().Set("Cache-Control", "no-store")
	writeJSON(w, http.StatusOK, result)
}

func (s *Server) handleBuildContactMatchCandidates(w http.ResponseWriter, r *http.Request) {
	builder, ok := s.store.(ContactMatchBuilder)
	if !ok {
		writeError(w, http.StatusServiceUnavailable, "identity_matches_unavailable",
			"Identity match review is unavailable")
		return
	}
	result, err := builder.BuildContactMatchCandidatesContext(r.Context())
	if err != nil {
		s.writeIdentityMatchError(w, err)
		return
	}
	w.Header().Set("Cache-Control", "no-store")
	writeJSON(w, http.StatusOK, result)
}

func (s *Server) handleListIdentityMatchCandidates(w http.ResponseWriter, r *http.Request) {
	matches, ok := s.identityMatchStore(w)
	if !ok {
		return
	}
	states, ok := identityMatchStates(w, r)
	if !ok {
		return
	}
	limit, _, err := queryInt(r, "limit")
	if err != nil {
		s.rejectBadParam(w, err)
		return
	}
	offset, _, err := queryInt(r, "offset")
	if err != nil {
		s.rejectBadParam(w, err)
		return
	}
	limit = clampIdentityMatchLimit(limit)
	if offset < 0 {
		offset = 0
	}
	origin := strings.TrimSpace(r.URL.Query().Get("origin"))
	if origin != "" && !slices.Contains(identityMatchOrigins, origin) {
		writeAPIHTTPError(w, apiHTTPErrorFromParam(
			enumParamError("origin", origin, identityMatchOrigins)))
		return
	}

	list := matches.ListIdentityMatchCandidatesContext
	switch origin {
	case identityMatchOriginContactMatch:
		list = matches.ListContactMatchCandidatesContext
	case identityMatchOriginPersonDuplicate:
		list = matches.ListPersonDuplicateCandidatesContext
	}
	candidates, err := list(r.Context(), states, limit, offset)
	if err != nil {
		s.writeIdentityMatchError(w, err)
		return
	}
	if candidates == nil {
		candidates = []store.IdentityMatchCandidate{}
	}
	endpoints, statuses, err := matches.DescribeIdentityMatchCandidatesContext(r.Context(), candidates)
	if err != nil {
		s.writeIdentityMatchError(w, err)
		return
	}
	w.Header().Set("Cache-Control", "no-store")
	writeJSON(w, http.StatusOK, IdentityMatchCandidatesResponse{
		Candidates: candidates, Endpoints: endpoints, ContactMatches: statuses,
		Limit: limit, Offset: offset,
	})
}

func (s *Server) handleAcceptIdentityMatchCandidate(w http.ResponseWriter, r *http.Request) {
	matches, ok := s.identityMatchStore(w)
	if !ok {
		return
	}
	id, ok := identityMatchCandidateID(w, r)
	if !ok {
		return
	}
	var request DecideIdentityMatchRequest
	if !decodeIdentityMatchRequest(w, r, &request) {
		return
	}
	// An HTTP accept is always an explicit user decision. The store also
	// refuses a system accept for every basis except a stable provider ID. The
	// store performs the binding check under the identity lock and restores the
	// prior decision if a merge is required, so this endpoint has no TOCTOU
	// preflight window.
	candidate, revision, err := matches.AcceptIdentityMatchCandidateContext(
		r.Context(), id, "user", request.Notes)
	if err != nil {
		if s.writePersonMergeRequired(w, r, err) {
			return
		}
		s.writeIdentityMatchError(w, err)
		return
	}
	w.Header().Set("Cache-Control", "no-store")
	writeJSON(w, http.StatusOK, IdentityMatchAcceptResponse{
		Candidate:        *candidate,
		IdentityRevision: revision,
		CacheState:       s.refreshIdentityCacheState(r.Context()),
	})
}

func (s *Server) handleRejectIdentityMatchCandidate(w http.ResponseWriter, r *http.Request) {
	matches, ok := s.identityMatchStore(w)
	if !ok {
		return
	}
	id, ok := identityMatchCandidateID(w, r)
	if !ok {
		return
	}
	var request DecideIdentityMatchRequest
	if !decodeIdentityMatchRequest(w, r, &request) {
		return
	}
	if _, err := matches.GetIdentityMatchCandidateContext(r.Context(), id); err != nil {
		s.writeIdentityMatchError(w, err)
		return
	}
	candidate, err := matches.DecideIdentityMatchCandidateContext(
		r.Context(), id, store.IdentityMatchStateRejected, "user", request.Notes)
	if err != nil {
		s.writeIdentityMatchError(w, err)
		return
	}
	afterRevision, err := matches.IdentityRevision()
	if err != nil {
		s.writeIdentityMatchError(w, err)
		return
	}
	w.Header().Set("Cache-Control", "no-store")
	writeJSON(w, http.StatusOK, IdentityMatchRejectResponse{
		Candidate:        *candidate,
		IdentityRevision: afterRevision,
		// RefreshIdentityDatasets is staleness-aware and skips publication
		// when the persisted cache already has this identity revision. Always
		// consulting it also lets a no-op retry repair a previously failed
		// refresh instead of incorrectly reporting the stale cache as ready.
		CacheState: s.refreshIdentityCacheState(r.Context()),
	})
}

func (s *Server) identityMatchStore(w http.ResponseWriter) (IdentityMatchStore, bool) {
	matches, ok := s.store.(IdentityMatchStore)
	if !ok {
		writeError(w, http.StatusServiceUnavailable, "identity_matches_unavailable",
			"Identity match review is unavailable")
	}
	return matches, ok
}

func clampIdentityMatchLimit(limit int) int {
	switch {
	case limit <= 0:
		return identityMatchDefaultLimit
	case limit > identityMatchMaxLimit:
		return identityMatchMaxLimit
	default:
		return limit
	}
}

// identityMatchStates parses the repeatable, optionally comma-separated state
// filter. An empty filter means every state.
func identityMatchStates(
	w http.ResponseWriter, r *http.Request,
) ([]store.IdentityMatchState, bool) {
	allowed := []string{
		string(store.IdentityMatchStateCandidate),
		string(store.IdentityMatchStateAccepted),
		string(store.IdentityMatchStateRejected),
		string(store.IdentityMatchStateConflict),
	}
	var states []store.IdentityMatchState
	for _, raw := range r.URL.Query()["state"] {
		for value := range strings.SplitSeq(raw, ",") {
			value = strings.TrimSpace(value)
			if value == "" {
				continue
			}
			if !slices.Contains(allowed, value) {
				writeAPIHTTPError(w, apiHTTPErrorFromParam(
					enumParamError("state", value, allowed)))
				return nil, false
			}
			states = append(states, store.IdentityMatchState(value))
		}
	}
	return states, true
}

func identityMatchCandidateID(w http.ResponseWriter, r *http.Request) (int64, bool) {
	id, err := strconv.ParseInt(r.PathValue("id"), 10, 64)
	if err != nil || id <= 0 {
		writeError(w, http.StatusBadRequest, "invalid_candidate_id",
			"Identity match candidate ID must be a positive integer")
		return 0, false
	}
	return id, true
}

// decodeIdentityMatchRequest decodes an optional decision body. Unknown fields
// are rejected so a typo in notes is never silently discarded.
func decodeIdentityMatchRequest(
	w http.ResponseWriter, r *http.Request, request *DecideIdentityMatchRequest,
) bool {
	body, err := io.ReadAll(http.MaxBytesReader(w, r.Body, 1<<20))
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid_request", "Invalid request body")
		return false
	}
	if len(bytes.TrimSpace(body)) == 0 {
		return true
	}
	decoder := jsontext.NewDecoder(bytes.NewReader(body), json.RejectUnknownMembers(true))

	if err := json.UnmarshalDecode(decoder, request); err != nil {
		writeError(w, http.StatusBadRequest, "invalid_request",
			"Invalid JSON request body: "+err.Error())
		return false
	}
	return requireSingleJSONValue(w, decoder, "invalid_request")
}

func (s *Server) writeIdentityMatchError(w http.ResponseWriter, err error) {
	if s.writeIfContextError(w, err) {
		return
	}
	switch {
	case errors.Is(err, store.ErrIdentityMatchNotFound):
		writeError(w, http.StatusNotFound, "identity_match_not_found",
			"Identity match candidate not found")
	case errors.Is(err, store.ErrIdentityMatchNotAcceptable):
		writeError(w, http.StatusConflict, "identity_match_not_acceptable",
			"This match needs stable provider corroboration or an explicit user decision")
	case errors.Is(err, store.ErrIdentityMatchAlreadyAccepted):
		writeError(w, http.StatusConflict, "identity_match_already_accepted",
			"An accepted identity match cannot be rejected because its participant link is retained")
	case errors.Is(err, store.ErrIdentityMatchAlreadyApplied):
		writeError(w, http.StatusConflict, "identity_match_already_applied",
			"An applied identity match must remain accepted while its participant link is retained")
	case errors.Is(err, store.ErrIdentityMatchNotAccepted):
		writeError(w, http.StatusConflict, "identity_match_state_changed",
			"The identity match changed before its participant link could be applied")
	case errors.Is(err, store.ErrIdentityMatchEndpointUnsupported):
		writeError(w, http.StatusConflict, "identity_match_endpoint_unsupported",
			"Only participant, participant-to-person, and CardDAV card matches can be applied")
	case errors.Is(err, store.ErrPersonCardDAVPublished):
		writeError(w, http.StatusConflict, "person_carddav_published",
			"Unpublish the person profile or resolve its CardDAV conflict before linking")
	case errors.Is(err, store.ErrContactMatchOwnerIdentity):
		writeError(w, http.StatusConflict, "contact_match_owner_identity",
			"The matched archive identity belongs to the archive owner and is not linked to contacts")
	case errors.Is(err, store.ErrContactMatchStale):
		writeError(w, http.StatusConflict, "contact_match_stale",
			"The profile's addresses no longer match this archive identity")
	case errors.Is(err, store.ErrContactMatchRejectedInCluster):
		writeError(w, http.StatusConflict, "contact_match_rejected_in_cluster",
			"Another identity in this cluster was already rejected for this profile")
	case errors.Is(err, store.ErrContactMatchNotAPerson):
		writeError(w, http.StatusConflict, "contact_match_not_a_person",
			"The matched archive identity is marked as not a person")
	case errors.Is(err, store.ErrContactMatchSharedMailbox):
		writeError(w, http.StatusConflict, "contact_match_shared_mailbox",
			"The matched address looks like a shared mailbox; mark it as not a person, or confirm it is a person, first")
	case errors.Is(err, store.ErrIdentityMatchEndpointNotFound):
		writeError(w, http.StatusNotFound, "identity_match_endpoint_not_found", err.Error())
	case errors.Is(err, store.ErrPersonBindingConflict):
		writeError(w, http.StatusConflict, "person_binding_conflict",
			"The identity clusters belong to different person profiles")
	case errors.Is(err, store.ErrParticipantNotFound), errors.Is(err, store.ErrInvalidParticipantID):
		writeError(w, http.StatusBadRequest, "invalid_participant_id", err.Error())
	case errors.Is(err, store.ErrInvalidIdentityMatchState):
		writeError(w, http.StatusBadRequest, "invalid_identity_match_state", err.Error())
	default:
		s.logger.Error("identity match operation failed", "error", err)
		writeError(w, http.StatusInternalServerError, "identity_match_failed",
			"Identity match operation failed")
	}
}
