package store

import (
	"context"
	"fmt"
	"slices"
	"strings"

	"go.kenn.io/msgvault/internal/textimport"
)

// Contact matching compares the exact email and phone contact points of
// contact-only profiles (persons with no bound participants, typically created
// by a CardDAV or vCard import) against observed participants. Exact
// identifiers are the only evidence: display names are never compared.

// ContactMatchSourceRef marks identity match candidates generated by contact
// matching, so they can be listed, refreshed, and reviewed as one queue.
const ContactMatchSourceRef = "contact_match"

// ContactMatchEvidenceKind is the evidence kind recorded for each contact
// point that exactly matched an observed participant identifier.
const ContactMatchEvidenceKind = "contact_point_match"

// ContactMatchClassification describes what accepting a contact match does,
// judged at participant-cluster level.
type ContactMatchClassification string

const (
	// ContactMatchBind means the matched cluster has no person: accepting it
	// binds the cluster to the contact profile.
	ContactMatchBind ContactMatchClassification = "bind"
	// ContactMatchMerge means the matched cluster already belongs to exactly
	// one other person: the two profiles must be merged by the user.
	ContactMatchMerge ContactMatchClassification = "merge"
	// ContactMatchAmbiguous means the matched cluster spans two or more
	// people, so no single merge resolves it.
	ContactMatchAmbiguous ContactMatchClassification = "ambiguous"
	// ContactMatchLinked means the cluster is already bound to the contact
	// profile; the match needs no further action.
	ContactMatchLinked ContactMatchClassification = "linked"
)

// ContactMatchBlockReason reports why a person merge would be refused for one
// side of a match.
type ContactMatchBlockReason string

const (
	ContactMatchBlockedPublished       ContactMatchBlockReason = "published"
	ContactMatchBlockedCardDAVConflict ContactMatchBlockReason = "carddav_conflict"
)

// ContactMatchIdentifier is one exact contact-point-to-participant match.
type ContactMatchIdentifier struct {
	ContactPointID  int64              `json:"contact_point_id"`
	ParticipantID   int64              `json:"participant_id"`
	Basis           IdentityMatchBasis `json:"basis"`
	NormalizedValue string             `json:"normalized_value"`
	// MatchedField names the participant field that matched:
	// participants.email_address, participants.phone_number, or
	// participant_identifiers.<type>.
	MatchedField string `json:"matched_field"`
	MatchedValue string `json:"matched_value"`
}

// ContactMatch is one contact-only profile matched to one participant
// cluster, with every identifier that supports it.
type ContactMatch struct {
	ContactPersonID  int64                      `json:"contact_person_id"`
	ParticipantID    int64                      `json:"participant_id"`
	ClusterMembers   []int64                    `json:"cluster_members"`
	ClusterPersonIDs []int64                    `json:"cluster_person_ids"`
	Classification   ContactMatchClassification `json:"classification"`
	BlockedReason    *ContactMatchBlockReason   `json:"blocked_reason,omitzero" nullable:"false"`
	Identifiers      []ContactMatchIdentifier   `json:"identifiers"`
}

type contactMatchPoint struct {
	id       int64
	personID int64
	kind     ContactAddressKind
	value    string
}

// FindContactMatchesContext lists every contact-only profile whose active
// email or phone contact point exactly matches an observed participant.
// Owner clusters and pairs the user already rejected are excluded. The result
// is read from one consistent snapshot and writes nothing.
func (s *Store) FindContactMatchesContext(ctx context.Context) ([]ContactMatch, error) {
	var matches []ContactMatch
	err := s.withReadSnapshotContext(ctx, func(tx *loggedTx) error {
		var err error
		matches, err = s.findContactMatchesTx(ctx, tx)
		return err
	})
	return matches, err
}

func (s *Store) findContactMatchesTx(ctx context.Context, tx *loggedTx) ([]ContactMatch, error) {
	points, err := contactOnlyContactPointsTx(ctx, tx)
	if err != nil || len(points) == 0 {
		return []ContactMatch{}, err
	}
	identifiers, err := contactMatchIdentifiersTx(ctx, tx, points)
	if err != nil || len(identifiers) == 0 {
		return []ContactMatch{}, err
	}
	owners, err := ownerParticipantIDsTx(ctx, tx)
	if err != nil {
		return nil, err
	}
	edges, err := s.loadLinkEdgesTxContext(ctx, tx)
	if err != nil {
		return nil, err
	}
	adjacency := buildAdjacency(edges)
	roots := clustersFromEdges(edges)
	clusterRoot := func(participantID int64) int64 {
		if root, ok := roots[participantID]; ok {
			return root
		}
		return participantID
	}
	members := map[int64][]int64{}
	clusterMembers := func(root int64) []int64 {
		if cached, ok := members[root]; ok {
			return cached
		}
		component := componentOfAdj(root, adjacency)
		ids := make([]int64, 0, len(component))
		for id := range component {
			ids = append(ids, id)
		}
		slices.Sort(ids)
		members[root] = ids
		return ids
	}

	pointPerson := make(map[int64]int64, len(points))
	for _, point := range points {
		pointPerson[point.id] = point.personID
	}
	type pairKey struct{ personID, root int64 }
	grouped := map[pairKey][]ContactMatchIdentifier{}
	keys := []pairKey{}
	for _, identifier := range identifiers {
		key := pairKey{
			personID: pointPerson[identifier.ContactPointID],
			root:     clusterRoot(identifier.ParticipantID),
		}
		if _, seen := grouped[key]; !seen {
			keys = append(keys, key)
		}
		grouped[key] = append(grouped[key], identifier)
	}

	allMembers := []int64{}
	for _, key := range keys {
		allMembers = append(allMembers, clusterMembers(key.root)...)
	}
	bindings, err := personBindingsForParticipantsTx(ctx, tx, allMembers)
	if err != nil {
		return nil, err
	}
	rejected, err := rejectedContactMatchPairsTx(ctx, tx)
	if err != nil {
		return nil, err
	}

	matches := make([]ContactMatch, 0, len(keys))
	personIDs := []int64{}
	for _, key := range keys {
		cluster := clusterMembers(key.root)
		if slices.ContainsFunc(cluster, func(id int64) bool {
			_, owner := owners[id]
			return owner
		}) {
			continue
		}
		if slices.ContainsFunc(cluster, func(id int64) bool {
			_, wasRejected := rejected[participantPersonPair{participantID: id, personID: key.personID}]
			return wasRejected
		}) {
			continue
		}
		clusterPersons := personsForMembers(cluster, bindings)
		found := grouped[key]
		sortContactMatchIdentifiers(found)
		match := ContactMatch{
			ContactPersonID:  key.personID,
			ParticipantID:    representativeContactMatchParticipant(found),
			ClusterMembers:   cluster,
			ClusterPersonIDs: clusterPersons,
			Classification:   classifyContactMatch(key.personID, clusterPersons),
			Identifiers:      found,
		}
		matches = append(matches, match)
		personIDs = append(personIDs, key.personID)
		personIDs = append(personIDs, clusterPersons...)
	}
	blocks, err := contactMatchBlockReasonsTx(ctx, tx, personIDs)
	if err != nil {
		return nil, err
	}
	for i := range matches {
		matches[i].BlockedReason = contactMatchBlockedReason(matches[i], blocks)
	}
	slices.SortFunc(matches, func(a, b ContactMatch) int {
		if a.ContactPersonID != b.ContactPersonID {
			return compareInt64(a.ContactPersonID, b.ContactPersonID)
		}
		return compareInt64(a.ParticipantID, b.ParticipantID)
	})
	return matches, nil
}

func compareInt64(a, b int64) int {
	switch {
	case a < b:
		return -1
	case a > b:
		return 1
	default:
		return 0
	}
}

// classifyContactMatch applies the cluster-level rule: bind when the cluster
// has no person, merge when it has exactly one other person, linked when it
// already belongs to the contact profile alone, ambiguous otherwise.
func classifyContactMatch(contactPersonID int64, clusterPersons []int64) ContactMatchClassification {
	switch {
	case len(clusterPersons) == 0:
		return ContactMatchBind
	case len(clusterPersons) == 1 && clusterPersons[0] == contactPersonID:
		return ContactMatchLinked
	case len(clusterPersons) == 1:
		return ContactMatchMerge
	default:
		return ContactMatchAmbiguous
	}
}

// contactMatchBlockedReason reports the first merge blocker on either side.
// Binding also merges into the contact profile, so the contact side is
// checked for every classification.
func contactMatchBlockedReason(
	match ContactMatch, blocks map[int64]ContactMatchBlockReason,
) *ContactMatchBlockReason {
	sides := []int64{match.ContactPersonID}
	if match.Classification == ContactMatchMerge {
		sides = append(sides, match.ClusterPersonIDs...)
	}
	for _, personID := range sides {
		if reason, ok := blocks[personID]; ok {
			return &reason
		}
	}
	return nil
}

func representativeContactMatchParticipant(identifiers []ContactMatchIdentifier) int64 {
	representative := identifiers[0].ParticipantID
	for _, identifier := range identifiers[1:] {
		representative = min(representative, identifier.ParticipantID)
	}
	return representative
}

func sortContactMatchIdentifiers(identifiers []ContactMatchIdentifier) {
	slices.SortFunc(identifiers, func(a, b ContactMatchIdentifier) int {
		// Email evidence first: the representative basis prefers it.
		if a.Basis != b.Basis {
			if a.Basis == IdentityMatchEmail {
				return -1
			}
			if b.Basis == IdentityMatchEmail {
				return 1
			}
		}
		if a.ParticipantID != b.ParticipantID {
			return compareInt64(a.ParticipantID, b.ParticipantID)
		}
		if a.ContactPointID != b.ContactPointID {
			return compareInt64(a.ContactPointID, b.ContactPointID)
		}
		return strings.Compare(a.MatchedField, b.MatchedField)
	})
}

// contactOnlyContactPointsTx loads the active email and phone contact points
// of persons that have no bound participant.
func contactOnlyContactPointsTx(ctx context.Context, tx *loggedTx) ([]contactMatchPoint, error) {
	rows, err := tx.QueryContext(ctx, `SELECT cp.id, cp.person_id, cp.address_kind, cp.normalized_value
		FROM person_contact_points cp
		WHERE cp.address_kind IN (?, ?)
		  AND cp.active_until IS NULL AND cp.superseded_at IS NULL
		  AND TRIM(cp.normalized_value) <> ''
		  AND NOT EXISTS (
			SELECT 1 FROM person_participants pp WHERE pp.person_id = cp.person_id
		  )
		ORDER BY cp.id`, ContactAddressEmail, ContactAddressPhone)
	if err != nil {
		return nil, fmt.Errorf("load contact-only contact points: %w", err)
	}
	defer func() { _ = rows.Close() }()
	points := []contactMatchPoint{}
	for rows.Next() {
		var point contactMatchPoint
		if err := rows.Scan(&point.id, &point.personID, &point.kind, &point.value); err != nil {
			return nil, fmt.Errorf("scan contact-only contact point: %w", err)
		}
		points = append(points, point)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate contact-only contact points: %w", err)
	}
	return points, nil
}

// contactMatchIdentifiersTx finds every participant field that exactly equals
// a contact point. Emails compare case-insensitively in SQL through the
// LOWER() expression indexes. Participant phones are mostly E.164 but not
// enforced, so they are normalized in Go with the same normalizer the contact
// points used.
func contactMatchIdentifiersTx(
	ctx context.Context, tx *loggedTx, points []contactMatchPoint,
) ([]ContactMatchIdentifier, error) {
	emails := map[string][]int64{}
	phones := map[string][]int64{}
	emailValues := []string{}
	for _, point := range points {
		switch point.kind {
		case ContactAddressEmail:
			value := strings.ToLower(strings.TrimSpace(point.value))
			if _, seen := emails[value]; !seen {
				emailValues = append(emailValues, value)
			}
			emails[value] = append(emails[value], point.id)
		case ContactAddressPhone:
			value, err := textimport.NormalizePhone(point.value)
			if err != nil {
				continue
			}
			phones[value] = append(phones[value], point.id)
		}
	}
	found := []ContactMatchIdentifier{}
	seen := map[ContactMatchIdentifier]struct{}{}
	add := func(pointIDs []int64, participantID int64, basis IdentityMatchBasis,
		normalized, field, raw string,
	) {
		for _, pointID := range pointIDs {
			identifier := ContactMatchIdentifier{
				ContactPointID: pointID, ParticipantID: participantID,
				Basis: basis, NormalizedValue: normalized,
				MatchedField: field, MatchedValue: raw,
			}
			if _, duplicate := seen[identifier]; duplicate {
				continue
			}
			seen[identifier] = struct{}{}
			found = append(found, identifier)
		}
	}

	if len(emailValues) > 0 {
		if err := queryInChunksContext(ctx, tx, emailValues, nil, `
			SELECT p.id, p.email_address FROM participants p
			WHERE p.email_address IS NOT NULL AND LOWER(p.email_address) IN (%s)
			ORDER BY p.id`, func(rows *loggedRows) error {
			var id int64
			var raw string
			if err := rows.Scan(&id, &raw); err != nil {
				return fmt.Errorf("scan participant email match: %w", err)
			}
			normalized := strings.ToLower(raw)
			add(emails[normalized], id, IdentityMatchEmail, normalized,
				"participants.email_address", raw)
			return nil
		}); err != nil {
			return nil, fmt.Errorf("match contact emails to participants: %w", err)
		}
		if err := queryInChunksContext(ctx, tx, emailValues, nil, `
			SELECT pi.participant_id, pi.identifier_value FROM participant_identifiers pi
			WHERE pi.identifier_type = 'email' AND LOWER(pi.identifier_value) IN (%s)
			ORDER BY pi.participant_id`, func(rows *loggedRows) error {
			var id int64
			var raw string
			if err := rows.Scan(&id, &raw); err != nil {
				return fmt.Errorf("scan participant email identifier match: %w", err)
			}
			normalized := strings.ToLower(raw)
			add(emails[normalized], id, IdentityMatchEmail, normalized,
				"participant_identifiers.email", raw)
			return nil
		}); err != nil {
			return nil, fmt.Errorf("match contact emails to participant identifiers: %w", err)
		}
	}

	if len(phones) > 0 {
		scanPhones := func(query, field string) error {
			rows, err := tx.QueryContext(ctx, query)
			if err != nil {
				return fmt.Errorf("load participant phones: %w", err)
			}
			defer func() { _ = rows.Close() }()
			for rows.Next() {
				var id int64
				var raw string
				if err := rows.Scan(&id, &raw); err != nil {
					return fmt.Errorf("scan participant phone: %w", err)
				}
				normalized, err := textimport.NormalizePhone(raw)
				if err != nil {
					continue
				}
				if pointIDs, ok := phones[normalized]; ok {
					add(pointIDs, id, IdentityMatchPhone, normalized, field, raw)
				}
			}
			return rows.Err()
		}
		if err := scanPhones(`SELECT id, phone_number FROM participants
			WHERE phone_number IS NOT NULL AND TRIM(phone_number) <> ''
			ORDER BY id`, "participants.phone_number"); err != nil {
			return nil, fmt.Errorf("match contact phones to participants: %w", err)
		}
		if err := scanPhones(`SELECT participant_id, identifier_value FROM participant_identifiers
			WHERE identifier_type = 'phone' AND TRIM(identifier_value) <> ''
			ORDER BY participant_id`, "participant_identifiers.phone"); err != nil {
			return nil, fmt.Errorf("match contact phones to participant identifiers: %w", err)
		}
	}
	return found, nil
}

// ownerParticipantIDsTx returns participants that carry one of the owner's
// confirmed account identities. It follows the owner_participants rule used
// by the analytics cache (build_cache.go ownerParticipantsSelectSQL): a
// participant's non-blank primary email matches case-insensitively, an email
// identifier matches only when the participant has no primary email, and any
// other identifier matches verbatim. Phone-shaped identities additionally
// match participant phones after normalization, since participant phones are
// not guaranteed to be stored in the account identity's form.
func ownerParticipantIDsTx(ctx context.Context, tx *loggedTx) (map[int64]struct{}, error) {
	owners := map[int64]struct{}{}
	rows, err := tx.QueryContext(ctx, `
		SELECT p.id FROM account_identities ai
		JOIN participants p
		  ON p.email_address IS NOT NULL
		 AND TRIM(p.email_address) <> ''
		 AND LOWER(p.email_address) = LOWER(ai.address)
		UNION
		SELECT pi.participant_id FROM account_identities ai
		JOIN participant_identifiers pi
		  ON (pi.identifier_type = 'email'
		      AND LOWER(pi.identifier_value) = LOWER(ai.address)
		      AND NOT EXISTS (
		          SELECT 1 FROM participants guard
		          WHERE guard.id = pi.participant_id
		            AND guard.email_address IS NOT NULL
		            AND TRIM(guard.email_address) <> ''
		      ))
		  OR (pi.identifier_type <> 'email' AND pi.identifier_value = ai.address)`)
	if err != nil {
		return nil, fmt.Errorf("load owner participants: %w", err)
	}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			_ = rows.Close()
			return nil, fmt.Errorf("scan owner participant: %w", err)
		}
		owners[id] = struct{}{}
	}
	if err := rows.Err(); err != nil {
		_ = rows.Close()
		return nil, fmt.Errorf("iterate owner participants: %w", err)
	}
	if err := rows.Close(); err != nil {
		return nil, fmt.Errorf("close owner participants: %w", err)
	}

	ownerPhones, err := ownerPhoneIdentitiesTx(ctx, tx)
	if err != nil || len(ownerPhones) == 0 {
		return owners, err
	}
	for _, query := range []string{
		`SELECT id, phone_number FROM participants
			WHERE phone_number IS NOT NULL AND TRIM(phone_number) <> ''`,
		`SELECT participant_id, identifier_value FROM participant_identifiers
			WHERE identifier_type = 'phone' AND TRIM(identifier_value) <> ''`,
	} {
		if err := func() error {
			rows, err := tx.QueryContext(ctx, query)
			if err != nil {
				return fmt.Errorf("load participant phones for owner match: %w", err)
			}
			defer func() { _ = rows.Close() }()
			for rows.Next() {
				var id int64
				var raw string
				if err := rows.Scan(&id, &raw); err != nil {
					return fmt.Errorf("scan participant phone for owner match: %w", err)
				}
				if normalized, err := textimport.NormalizePhone(raw); err == nil {
					if _, owner := ownerPhones[normalized]; owner {
						owners[id] = struct{}{}
					}
				}
			}
			return rows.Err()
		}(); err != nil {
			return nil, err
		}
	}
	return owners, nil
}

func ownerPhoneIdentitiesTx(ctx context.Context, tx *loggedTx) (map[string]struct{}, error) {
	rows, err := tx.QueryContext(ctx, `SELECT address FROM account_identities`)
	if err != nil {
		return nil, fmt.Errorf("load owner identities: %w", err)
	}
	defer func() { _ = rows.Close() }()
	phones := map[string]struct{}{}
	for rows.Next() {
		var address string
		if err := rows.Scan(&address); err != nil {
			return nil, fmt.Errorf("scan owner identity: %w", err)
		}
		if !phoneShaped(address) {
			continue
		}
		if normalized, err := textimport.NormalizePhone(address); err == nil {
			phones[normalized] = struct{}{}
		}
	}
	return phones, rows.Err()
}

// phoneShaped reports whether a value contains only phone punctuation and
// digits, so that a numeric username is never read as a phone number.
func phoneShaped(value string) bool {
	value = strings.TrimSpace(value)
	if value == "" {
		return false
	}
	digits := 0
	for _, r := range value {
		switch {
		case r >= '0' && r <= '9':
			digits++
		case strings.ContainsRune("+-(). ", r):
		default:
			return false
		}
	}
	return digits >= 7
}

// personBindingsForParticipantsTx maps each bound participant to its persons.
func personBindingsForParticipantsTx(
	ctx context.Context, tx *loggedTx, participantIDs []int64,
) (map[int64][]int64, error) {
	ids := slices.Clone(participantIDs)
	slices.Sort(ids)
	ids = slices.Compact(ids)
	bindings := map[int64][]int64{}
	if err := queryInChunksContext(ctx, tx, ids, nil, `
		SELECT participant_id, person_id FROM person_participants
		WHERE participant_id IN (%s)
		ORDER BY participant_id, person_id`, func(rows *loggedRows) error {
		var participantID, personID int64
		if err := rows.Scan(&participantID, &personID); err != nil {
			return fmt.Errorf("scan participant person binding: %w", err)
		}
		bindings[participantID] = append(bindings[participantID], personID)
		return nil
	}); err != nil {
		return nil, fmt.Errorf("load participant person bindings: %w", err)
	}
	return bindings, nil
}

func personsForMembers(members []int64, bindings map[int64][]int64) []int64 {
	persons := []int64{}
	for _, member := range members {
		persons = append(persons, bindings[member]...)
	}
	slices.Sort(persons)
	return slices.Compact(persons)
}

type participantPersonPair struct {
	participantID, personID int64
}

// rejectedContactMatchPairsTx loads every rejected participant-to-person
// decision. A rejection of any member of a cluster suppresses the whole
// cluster for that person, whichever identifier produced it.
func rejectedContactMatchPairsTx(
	ctx context.Context, tx *loggedTx,
) (map[participantPersonPair]struct{}, error) {
	rows, err := tx.QueryContext(ctx, `SELECT left_id, right_id FROM identity_match_candidates
		WHERE state = ? AND left_kind = ? AND right_kind = ?`,
		IdentityMatchStateRejected, IdentityMatchParticipant, IdentityMatchPerson)
	if err != nil {
		return nil, fmt.Errorf("load rejected participant-to-person matches: %w", err)
	}
	defer func() { _ = rows.Close() }()
	rejected := map[participantPersonPair]struct{}{}
	for rows.Next() {
		var pair participantPersonPair
		if err := rows.Scan(&pair.participantID, &pair.personID); err != nil {
			return nil, fmt.Errorf("scan rejected participant-to-person match: %w", err)
		}
		rejected[pair] = struct{}{}
	}
	return rejected, rows.Err()
}

// contactMatchBlockReasonsTx reports people a person merge would refuse: a
// CardDAV publication or an unresolved CardDAV conflict with local intent.
// It mirrors ensurePersonMergeCardDAVStateTx so the queue shows the same
// verdict the merge would return.
func contactMatchBlockReasonsTx(
	ctx context.Context, tx *loggedTx, personIDs []int64,
) (map[int64]ContactMatchBlockReason, error) {
	ids := slices.Clone(personIDs)
	slices.Sort(ids)
	ids = slices.Compact(ids)
	blocks := map[int64]ContactMatchBlockReason{}
	if err := queryInChunksContext(ctx, tx, ids, nil, `
		SELECT r.person_id FROM carddav_conflicts c
		JOIN carddav_resources r ON r.address_book_id = c.address_book_id AND r.href = c.href
		WHERE c.status = 'unresolved' AND c.local_mutation_intent IS NOT NULL
		  AND r.person_id IN (%s)`, func(rows *loggedRows) error {
		var personID int64
		if err := rows.Scan(&personID); err != nil {
			return fmt.Errorf("scan CardDAV conflict person: %w", err)
		}
		blocks[personID] = ContactMatchBlockedCardDAVConflict
		return nil
	}); err != nil {
		return nil, fmt.Errorf("load contact match CardDAV conflicts: %w", err)
	}
	if err := queryInChunksContext(ctx, tx, ids, nil, `
		SELECT person_id FROM carddav_publications WHERE person_id IN (%s)`,
		func(rows *loggedRows) error {
			var personID int64
			if err := rows.Scan(&personID); err != nil {
				return fmt.Errorf("scan CardDAV publication person: %w", err)
			}
			blocks[personID] = ContactMatchBlockedPublished
			return nil
		}); err != nil {
		return nil, fmt.Errorf("load contact match CardDAV publications: %w", err)
	}
	return blocks, nil
}
