package store

import (
	"context"
	"errors"
	"fmt"
	"slices"
	"strings"

	"go.kenn.io/msgvault/internal/correspondentkind"
	"go.kenn.io/msgvault/internal/textimport"
)

// Contact matching compares the exact email and phone contact points of
// contact-only profiles (persons with no bound participants, typically created
// by a CardDAV or vCard import) against observed participants. Exact
// identifiers are the only evidence: display names are never compared.

// ContactMatchSourceRef marks identity match candidates generated by contact
// matching, so they can be listed, refreshed, and reviewed as one queue.
const ContactMatchSourceRef = "contact_match"

// ContactMatchEvidenceKind is the evidence kind recorded for each contact
// point that exactly matched an observed participant identifier.
const ContactMatchEvidenceKind = "contact_point_match"

// ContactMatchClassification describes what accepting a contact match does,
// judged at participant-cluster level.
type ContactMatchClassification string

const (
	// ContactMatchBind means the matched cluster has no person: accepting it
	// binds the cluster to the contact profile.
	ContactMatchBind ContactMatchClassification = "bind"
	// ContactMatchMerge means the matched cluster already belongs to exactly
	// one other person: the two profiles are one human. An exact-email match
	// the rule can decide is merged automatically; any other waits for the
	// user to merge.
	ContactMatchMerge ContactMatchClassification = "merge"
	// ContactMatchAmbiguous means the matched cluster spans two or more
	// people, so no single merge resolves it.
	ContactMatchAmbiguous ContactMatchClassification = "ambiguous"
	// ContactMatchLinked means the cluster is already bound to the contact
	// profile; the match needs no further action.
	ContactMatchLinked ContactMatchClassification = "linked"
	// ContactMatchSharedMailbox means the matched address looks like a
	// mailbox several people write from (see
	// correspondentkind.DetectSharedMailbox). Nothing is bound or merged
	// through it: the reviewer marks it as not a person, or says it is a
	// person, first.
	ContactMatchSharedMailbox ContactMatchClassification = "shared_mailbox"
)

// ContactMatchBlockReason reports why a person merge would be refused for one
// side of a match.
type ContactMatchBlockReason string

const (
	ContactMatchBlockedPublished       ContactMatchBlockReason = "published"
	ContactMatchBlockedCardDAVConflict ContactMatchBlockReason = "carddav_conflict"
)

// ContactMatchIdentifier is one exact contact-point-to-participant match.
type ContactMatchIdentifier struct {
	ContactPointID  int64              `json:"contact_point_id"`
	ParticipantID   int64              `json:"participant_id"`
	Basis           IdentityMatchBasis `json:"basis"`
	NormalizedValue string             `json:"normalized_value"`
	// MatchedField names the participant field that matched:
	// participants.email_address, participants.phone_number, or
	// participant_identifiers.<type>.
	MatchedField string `json:"matched_field"`
	MatchedValue string `json:"matched_value"`
}

// ContactMatch is one contact-only profile matched to one participant
// cluster, with every identifier that supports it.
type ContactMatch struct {
	ContactPersonID  int64                      `json:"contact_person_id"`
	ParticipantID    int64                      `json:"participant_id"`
	ClusterMembers   []int64                    `json:"cluster_members"`
	ClusterPersonIDs []int64                    `json:"cluster_person_ids"`
	Classification   ContactMatchClassification `json:"classification"`
	BlockedReason    *ContactMatchBlockReason   `json:"blocked_reason,omitzero" nullable:"false"`
	Identifiers      []ContactMatchIdentifier   `json:"identifiers"`
	// SharedMailbox explains a shared_mailbox classification.
	SharedMailbox *correspondentkind.SharedMailboxSignal `json:"shared_mailbox,omitzero" nullable:"false"`

	// The exact-match rule's one-to-one evidence, counted before the
	// owner, rejection, and not-a-person filters drop any pair: the
	// identity clusters the contact's emails hit, the contact profiles the
	// cluster's emails hit, and whether a contact phone hits a cluster that
	// belongs to a different person.
	autoEmailClusters int
	autoEmailContacts int
	autoPhoneConflict bool
}

type contactMatchPoint struct {
	id       int64
	personID int64
	kind     ContactAddressKind
	value    string
}

// FindContactMatchesContext lists every contact-only profile whose active
// email or phone contact point exactly matches an observed participant.
// Owner clusters and pairs the user already rejected are excluded. The result
// is read from one consistent snapshot and writes nothing.
func (s *Store) FindContactMatchesContext(ctx context.Context) ([]ContactMatch, error) {
	var matches []ContactMatch
	err := s.withReadSnapshotContext(ctx, func(tx *loggedTx) error {
		var err error
		matches, err = s.findContactMatchesTx(ctx, tx)
		return err
	})
	return matches, err
}

func (s *Store) findContactMatchesTx(ctx context.Context, tx *loggedTx) ([]ContactMatch, error) {
	points, err := contactOnlyContactPointsTx(ctx, tx)
	if err != nil {
		return nil, err
	}
	return s.findContactMatchesForPointsTx(ctx, tx, points)
}

// findContactMatchesForPointsTx matches the given contact-only contact
// points. The one-to-one evidence of each match counts only these points, so
// a caller re-checking one pair passes every point that can change it (see
// contactMatchPointsForPairTx).
func (s *Store) findContactMatchesForPointsTx(
	ctx context.Context, tx *loggedTx, points []contactMatchPoint,
) ([]ContactMatch, error) {
	if len(points) == 0 {
		return []ContactMatch{}, nil
	}
	identifiers, err := contactMatchIdentifiersTx(ctx, tx, points)
	if err != nil || len(identifiers) == 0 {
		return []ContactMatch{}, err
	}
	owners, err := ownerParticipantIDsTx(ctx, tx)
	if err != nil {
		return nil, err
	}
	edges, err := s.loadLinkEdgesTxContext(ctx, tx)
	if err != nil {
		return nil, err
	}
	adjacency := buildAdjacency(edges)
	roots := clustersFromEdges(edges)
	clusterRoot := func(participantID int64) int64 {
		if root, ok := roots[participantID]; ok {
			return root
		}
		return participantID
	}
	members := map[int64][]int64{}
	clusterMembers := func(root int64) []int64 {
		if cached, ok := members[root]; ok {
			return cached
		}
		component := componentOfAdj(root, adjacency)
		ids := make([]int64, 0, len(component))
		for id := range component {
			ids = append(ids, id)
		}
		slices.Sort(ids)
		members[root] = ids
		return ids
	}

	pointPerson := make(map[int64]int64, len(points))
	for _, point := range points {
		pointPerson[point.id] = point.personID
	}
	type pairKey struct{ personID, root int64 }
	grouped := map[pairKey][]ContactMatchIdentifier{}
	keys := []pairKey{}
	for _, identifier := range identifiers {
		key := pairKey{
			personID: pointPerson[identifier.ContactPointID],
			root:     clusterRoot(identifier.ParticipantID),
		}
		if _, seen := grouped[key]; !seen {
			keys = append(keys, key)
		}
		grouped[key] = append(grouped[key], identifier)
	}

	allMembers := []int64{}
	for _, key := range keys {
		allMembers = append(allMembers, clusterMembers(key.root)...)
	}
	bindings, err := personBindingsForParticipantsTx(ctx, tx, allMembers)
	if err != nil {
		return nil, err
	}
	rejected, err := rejectedContactMatchPairsTx(ctx, tx)
	if err != nil {
		return nil, err
	}
	// Only a user decision holds a cluster back from contact matching; a
	// rule or Jev classification never resolves an identity match.
	notPeople, err := s.userHiddenCorrespondentParticipantsTx(ctx, tx)
	if err != nil {
		return nil, err
	}

	// Raw one-to-one evidence for the exact-match rule, from every pair
	// before any filter below drops one.
	emailRoots := map[int64]map[int64]struct{}{}
	emailContacts := map[int64]map[int64]struct{}{}
	phoneRoots := map[int64]map[int64]struct{}{}
	addTo := func(target map[int64]map[int64]struct{}, key, value int64) {
		if target[key] == nil {
			target[key] = map[int64]struct{}{}
		}
		target[key][value] = struct{}{}
	}
	for _, key := range keys {
		for _, identifier := range grouped[key] {
			switch identifier.Basis {
			case IdentityMatchEmail:
				addTo(emailRoots, key.personID, key.root)
				addTo(emailContacts, key.root, key.personID)
			case IdentityMatchPhone:
				addTo(phoneRoots, key.personID, key.root)
			default:
			}
		}
	}
	phoneConflict := func(contactID, root int64, clusterPersons []int64) bool {
		for other := range phoneRoots[contactID] {
			if other == root {
				continue
			}
			otherPersons := personsForMembers(clusterMembers(other), bindings)
			if len(otherPersons) == 0 {
				continue
			}
			if !slices.Equal(otherPersons, clusterPersons) {
				return true
			}
		}
		return false
	}

	matches := make([]ContactMatch, 0, len(keys))
	personIDs := []int64{}
	signalClusters := map[int64][]int64{}
	for _, key := range keys {
		cluster := clusterMembers(key.root)
		if slices.ContainsFunc(cluster, func(id int64) bool {
			_, owner := owners[id]
			return owner
		}) {
			continue
		}
		if slices.ContainsFunc(cluster, func(id int64) bool {
			_, wasRejected := rejected[participantPersonPair{participantID: id, personID: key.personID}]
			return wasRejected
		}) {
			continue
		}
		// A cluster the user said is not a person is never bound or merged.
		if slices.ContainsFunc(cluster, func(id int64) bool {
			_, hidden := notPeople[id]
			return hidden
		}) {
			continue
		}
		clusterPersons := personsForMembers(cluster, bindings)
		found := grouped[key]
		sortContactMatchIdentifiers(found)
		match := ContactMatch{
			ContactPersonID:  key.personID,
			ParticipantID:    representativeContactMatchParticipant(found),
			ClusterMembers:   cluster,
			ClusterPersonIDs: clusterPersons,
			Classification:   classifyContactMatch(key.personID, clusterPersons),
			Identifiers:      found,

			autoEmailClusters: len(emailRoots[key.personID]),
			autoEmailContacts: len(emailContacts[key.root]),
			autoPhoneConflict: phoneConflict(key.personID, key.root, clusterPersons),
		}
		matches = append(matches, match)
		personIDs = append(personIDs, key.personID)
		personIDs = append(personIDs, clusterPersons...)
		signalClusters[key.root] = cluster
	}
	signals, err := s.sharedMailboxSignalsTx(ctx, tx, signalClusters)
	if err != nil {
		return nil, err
	}
	for i := range matches {
		signal, fires := signals[matches[i].ClusterMembers[0]]
		if fires && matches[i].Classification != ContactMatchLinked {
			matches[i].Classification = ContactMatchSharedMailbox
			matches[i].SharedMailbox = &signal
		}
	}
	blocks, err := contactMatchBlockReasonsTx(ctx, tx, personIDs)
	if err != nil {
		return nil, err
	}
	for i := range matches {
		matches[i].BlockedReason = contactMatchBlockedReason(matches[i], blocks)
	}
	slices.SortFunc(matches, func(a, b ContactMatch) int {
		if a.ContactPersonID != b.ContactPersonID {
			return compareInt64(a.ContactPersonID, b.ContactPersonID)
		}
		return compareInt64(a.ParticipantID, b.ParticipantID)
	})
	return matches, nil
}

func compareInt64(a, b int64) int {
	switch {
	case a < b:
		return -1
	case a > b:
		return 1
	default:
		return 0
	}
}

// classifyContactMatch applies the cluster-level rule: bind when the cluster
// has no person, merge when it has exactly one other person, linked when it
// already belongs to the contact profile alone, ambiguous otherwise.
func classifyContactMatch(contactPersonID int64, clusterPersons []int64) ContactMatchClassification {
	switch {
	case len(clusterPersons) == 0:
		return ContactMatchBind
	case len(clusterPersons) == 1 && clusterPersons[0] == contactPersonID:
		return ContactMatchLinked
	case len(clusterPersons) == 1:
		return ContactMatchMerge
	default:
		return ContactMatchAmbiguous
	}
}

// contactMatchBlockedReason reports the first merge blocker on either side.
// Binding also merges into the contact profile, so the contact side is
// checked for every classification.
func contactMatchBlockedReason(
	match ContactMatch, blocks map[int64]ContactMatchBlockReason,
) *ContactMatchBlockReason {
	sides := []int64{match.ContactPersonID}
	if match.Classification == ContactMatchMerge {
		sides = append(sides, match.ClusterPersonIDs...)
	}
	for _, personID := range sides {
		if reason, ok := blocks[personID]; ok {
			return &reason
		}
	}
	return nil
}

func representativeContactMatchParticipant(identifiers []ContactMatchIdentifier) int64 {
	representative := identifiers[0].ParticipantID
	for _, identifier := range identifiers[1:] {
		representative = min(representative, identifier.ParticipantID)
	}
	return representative
}

func sortContactMatchIdentifiers(identifiers []ContactMatchIdentifier) {
	slices.SortFunc(identifiers, func(a, b ContactMatchIdentifier) int {
		// Email evidence first: the representative basis prefers it.
		if a.Basis != b.Basis {
			if a.Basis == IdentityMatchEmail {
				return -1
			}
			if b.Basis == IdentityMatchEmail {
				return 1
			}
		}
		if a.ParticipantID != b.ParticipantID {
			return compareInt64(a.ParticipantID, b.ParticipantID)
		}
		if a.ContactPointID != b.ContactPointID {
			return compareInt64(a.ContactPointID, b.ContactPointID)
		}
		return strings.Compare(a.MatchedField, b.MatchedField)
	})
}

// contactOnlyPointsSelect selects the active email and phone contact points
// of persons that have no bound participant.
const contactOnlyPointsSelect = `SELECT cp.id, cp.person_id, cp.address_kind, cp.normalized_value
		FROM person_contact_points cp
		WHERE cp.address_kind IN (?, ?)
		  AND cp.active_until IS NULL AND cp.superseded_at IS NULL
		  AND TRIM(cp.normalized_value) <> ''
		  AND NOT EXISTS (
			SELECT 1 FROM person_participants pp WHERE pp.person_id = cp.person_id
		  )`

func scanContactMatchPoint(rows *loggedRows) (contactMatchPoint, error) {
	var point contactMatchPoint
	if err := rows.Scan(&point.id, &point.personID, &point.kind, &point.value); err != nil {
		return point, fmt.Errorf("scan contact-only contact point: %w", err)
	}
	return point, nil
}

// contactOnlyContactPointsTx loads the active email and phone contact points
// of persons that have no bound participant.
func contactOnlyContactPointsTx(ctx context.Context, tx *loggedTx) ([]contactMatchPoint, error) {
	rows, err := tx.QueryContext(ctx, contactOnlyPointsSelect+` ORDER BY cp.id`,
		ContactAddressEmail, ContactAddressPhone)
	if err != nil {
		return nil, fmt.Errorf("load contact-only contact points: %w", err)
	}
	defer func() { _ = rows.Close() }()
	points := []contactMatchPoint{}
	for rows.Next() {
		point, err := scanContactMatchPoint(rows)
		if err != nil {
			return nil, err
		}
		points = append(points, point)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate contact-only contact points: %w", err)
	}
	return points, nil
}

// contactMatchPointsForPairTx loads the contact-only points that decide one
// contact profile and identity cluster pair: every point of the contact
// (which identity clusters its emails and phones reach) and every email
// point of any contact profile that lists one of the cluster's addresses
// (which contacts reach the cluster).
func contactMatchPointsForPairTx(
	ctx context.Context, tx *loggedTx, contactPersonID int64, members []int64,
) ([]contactMatchPoint, error) {
	emails := []string{}
	seenEmail := map[string]struct{}{}
	collect := func(rows *loggedRows) error {
		var email string
		if err := rows.Scan(&email); err != nil {
			return fmt.Errorf("scan cluster email: %w", err)
		}
		if _, seen := seenEmail[email]; !seen && email != "" {
			seenEmail[email] = struct{}{}
			emails = append(emails, email)
		}
		return nil
	}
	if err := queryInChunksContext(ctx, tx, members, nil, `
		SELECT LOWER(TRIM(email_address)) FROM participants
		WHERE email_address IS NOT NULL AND id IN (%s)`, collect); err != nil {
		return nil, fmt.Errorf("load cluster emails: %w", err)
	}
	if err := queryInChunksContext(ctx, tx, members, nil, `
		SELECT LOWER(TRIM(identifier_value)) FROM participant_identifiers
		WHERE identifier_type = 'email' AND participant_id IN (%s)`, collect); err != nil {
		return nil, fmt.Errorf("load cluster email identifiers: %w", err)
	}

	points := []contactMatchPoint{}
	seenPoint := map[int64]struct{}{}
	add := func(rows *loggedRows) error {
		point, err := scanContactMatchPoint(rows)
		if err != nil {
			return err
		}
		if _, seen := seenPoint[point.id]; !seen {
			seenPoint[point.id] = struct{}{}
			points = append(points, point)
		}
		return nil
	}
	if err := queryInChunksContext(ctx, tx, []int64{contactPersonID},
		[]any{ContactAddressEmail, ContactAddressPhone},
		contactOnlyPointsSelect+` AND cp.person_id IN (%s)`, add); err != nil {
		return nil, fmt.Errorf("load contact profile points: %w", err)
	}
	if err := queryInChunksContext(ctx, tx, emails,
		[]any{ContactAddressEmail, ContactAddressPhone, ContactAddressEmail},
		contactOnlyPointsSelect+` AND cp.address_kind = ?
		  AND LOWER(TRIM(cp.normalized_value)) IN (%s)`, add); err != nil {
		return nil, fmt.Errorf("load contact points listing cluster emails: %w", err)
	}
	slices.SortFunc(points, func(a, b contactMatchPoint) int { return compareInt64(a.id, b.id) })
	return points, nil
}

// contactMatchIdentifiersTx finds every participant field that exactly equals
// a contact point. Emails compare case-insensitively in SQL through the
// LOWER() expression indexes. Participant phones are mostly E.164 but not
// enforced, so they are normalized in Go with the same normalizer the contact
// points used.
func contactMatchIdentifiersTx(
	ctx context.Context, tx *loggedTx, points []contactMatchPoint,
) ([]ContactMatchIdentifier, error) {
	emails := map[string][]int64{}
	phones := map[string][]int64{}
	emailValues := []string{}
	for _, point := range points {
		switch point.kind {
		case ContactAddressEmail:
			value := strings.ToLower(strings.TrimSpace(point.value))
			if _, seen := emails[value]; !seen {
				emailValues = append(emailValues, value)
			}
			emails[value] = append(emails[value], point.id)
		case ContactAddressPhone:
			value, err := textimport.NormalizePhone(point.value)
			if err != nil {
				continue
			}
			phones[value] = append(phones[value], point.id)
		default:
			// The loader selects only email and phone contact points.
		}
	}
	found := []ContactMatchIdentifier{}
	seen := map[ContactMatchIdentifier]struct{}{}
	add := func(pointIDs []int64, participantID int64, basis IdentityMatchBasis,
		normalized, field, raw string,
	) {
		for _, pointID := range pointIDs {
			identifier := ContactMatchIdentifier{
				ContactPointID: pointID, ParticipantID: participantID,
				Basis: basis, NormalizedValue: normalized,
				MatchedField: field, MatchedValue: raw,
			}
			if _, duplicate := seen[identifier]; duplicate {
				continue
			}
			seen[identifier] = struct{}{}
			found = append(found, identifier)
		}
	}

	if len(emailValues) > 0 {
		if err := queryInChunksContext(ctx, tx, emailValues, nil, `
			SELECT p.id, p.email_address FROM participants p
			WHERE p.email_address IS NOT NULL AND LOWER(p.email_address) IN (%s)
			ORDER BY p.id`, func(rows *loggedRows) error {
			var id int64
			var raw string
			if err := rows.Scan(&id, &raw); err != nil {
				return fmt.Errorf("scan participant email match: %w", err)
			}
			normalized := strings.ToLower(raw)
			add(emails[normalized], id, IdentityMatchEmail, normalized,
				"participants.email_address", raw)
			return nil
		}); err != nil {
			return nil, fmt.Errorf("match contact emails to participants: %w", err)
		}
		if err := queryInChunksContext(ctx, tx, emailValues, nil, `
			SELECT pi.participant_id, pi.identifier_value FROM participant_identifiers pi
			WHERE pi.identifier_type = 'email' AND LOWER(pi.identifier_value) IN (%s)
			ORDER BY pi.participant_id`, func(rows *loggedRows) error {
			var id int64
			var raw string
			if err := rows.Scan(&id, &raw); err != nil {
				return fmt.Errorf("scan participant email identifier match: %w", err)
			}
			normalized := strings.ToLower(raw)
			add(emails[normalized], id, IdentityMatchEmail, normalized,
				"participant_identifiers.email", raw)
			return nil
		}); err != nil {
			return nil, fmt.Errorf("match contact emails to participant identifiers: %w", err)
		}
	}

	if len(phones) > 0 {
		scanPhones := func(query, field string) error {
			rows, err := tx.QueryContext(ctx, query)
			if err != nil {
				return fmt.Errorf("load participant phones: %w", err)
			}
			defer func() { _ = rows.Close() }()
			for rows.Next() {
				var id int64
				var raw string
				if err := rows.Scan(&id, &raw); err != nil {
					return fmt.Errorf("scan participant phone: %w", err)
				}
				normalized, err := textimport.NormalizePhone(raw)
				if err != nil {
					continue
				}
				if pointIDs, ok := phones[normalized]; ok {
					add(pointIDs, id, IdentityMatchPhone, normalized, field, raw)
				}
			}
			return rows.Err()
		}
		if err := scanPhones(`SELECT id, phone_number FROM participants
			WHERE phone_number IS NOT NULL AND TRIM(phone_number) <> ''
			ORDER BY id`, "participants.phone_number"); err != nil {
			return nil, fmt.Errorf("match contact phones to participants: %w", err)
		}
		if err := scanPhones(`SELECT participant_id, identifier_value FROM participant_identifiers
			WHERE identifier_type = 'phone' AND TRIM(identifier_value) <> ''
			ORDER BY participant_id`, "participant_identifiers.phone"); err != nil {
			return nil, fmt.Errorf("match contact phones to participant identifiers: %w", err)
		}
	}
	return found, nil
}

// ownerParticipantIDsTx returns participants that carry one of the owner's
// confirmed account identities. It follows the owner_participants rule used
// by the analytics cache (build_cache.go ownerParticipantsSelectSQL): a
// participant's non-blank primary email matches case-insensitively, an email
// identifier matches only when the participant has no primary email, and any
// other identifier matches verbatim. Phone-shaped identities additionally
// match participant phones after normalization, since participant phones are
// not guaranteed to be stored in the account identity's form.
func ownerParticipantIDsTx(ctx context.Context, tx *loggedTx) (map[int64]struct{}, error) {
	owners := map[int64]struct{}{}
	rows, err := tx.QueryContext(ctx, `
		SELECT p.id FROM account_identities ai
		JOIN participants p
		  ON p.email_address IS NOT NULL
		 AND TRIM(p.email_address) <> ''
		 AND LOWER(p.email_address) = LOWER(ai.address)
		UNION
		SELECT pi.participant_id FROM account_identities ai
		JOIN participant_identifiers pi
		  ON (pi.identifier_type = 'email'
		      AND LOWER(pi.identifier_value) = LOWER(ai.address)
		      AND NOT EXISTS (
		          SELECT 1 FROM participants guard
		          WHERE guard.id = pi.participant_id
		            AND guard.email_address IS NOT NULL
		            AND TRIM(guard.email_address) <> ''
		      ))
		  OR (pi.identifier_type <> 'email' AND pi.identifier_value = ai.address)`)
	if err != nil {
		return nil, fmt.Errorf("load owner participants: %w", err)
	}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			_ = rows.Close()
			return nil, fmt.Errorf("scan owner participant: %w", err)
		}
		owners[id] = struct{}{}
	}
	if err := rows.Err(); err != nil {
		_ = rows.Close()
		return nil, fmt.Errorf("iterate owner participants: %w", err)
	}
	if err := rows.Close(); err != nil {
		return nil, fmt.Errorf("close owner participants: %w", err)
	}

	ownerPhones, err := ownerPhoneIdentitiesTx(ctx, tx)
	if err != nil || len(ownerPhones) == 0 {
		return owners, err
	}
	for _, query := range []string{
		`SELECT id, phone_number FROM participants
			WHERE phone_number IS NOT NULL AND TRIM(phone_number) <> ''`,
		`SELECT participant_id, identifier_value FROM participant_identifiers
			WHERE identifier_type = 'phone' AND TRIM(identifier_value) <> ''`,
	} {
		if err := func() error {
			rows, err := tx.QueryContext(ctx, query)
			if err != nil {
				return fmt.Errorf("load participant phones for owner match: %w", err)
			}
			defer func() { _ = rows.Close() }()
			for rows.Next() {
				var id int64
				var raw string
				if err := rows.Scan(&id, &raw); err != nil {
					return fmt.Errorf("scan participant phone for owner match: %w", err)
				}
				if normalized, err := textimport.NormalizePhone(raw); err == nil {
					if _, owner := ownerPhones[normalized]; owner {
						owners[id] = struct{}{}
					}
				}
			}
			return rows.Err()
		}(); err != nil {
			return nil, err
		}
	}
	return owners, nil
}

func ownerPhoneIdentitiesTx(ctx context.Context, tx *loggedTx) (map[string]struct{}, error) {
	rows, err := tx.QueryContext(ctx, `SELECT address FROM account_identities`)
	if err != nil {
		return nil, fmt.Errorf("load owner identities: %w", err)
	}
	defer func() { _ = rows.Close() }()
	phones := map[string]struct{}{}
	for rows.Next() {
		var address string
		if err := rows.Scan(&address); err != nil {
			return nil, fmt.Errorf("scan owner identity: %w", err)
		}
		if !phoneShaped(address) {
			continue
		}
		if normalized, err := textimport.NormalizePhone(address); err == nil {
			phones[normalized] = struct{}{}
		}
	}
	return phones, rows.Err()
}

// phoneShaped reports whether a value contains only phone punctuation and
// digits, so that a numeric username is never read as a phone number.
func phoneShaped(value string) bool {
	value = strings.TrimSpace(value)
	if value == "" {
		return false
	}
	digits := 0
	for _, r := range value {
		switch {
		case r >= '0' && r <= '9':
			digits++
		case strings.ContainsRune("+-(). ", r):
		default:
			return false
		}
	}
	return digits >= 7
}

// personBindingsForParticipantsTx maps each bound participant to its persons.
func personBindingsForParticipantsTx(
	ctx context.Context, tx *loggedTx, participantIDs []int64,
) (map[int64][]int64, error) {
	ids := slices.Clone(participantIDs)
	slices.Sort(ids)
	ids = slices.Compact(ids)
	bindings := map[int64][]int64{}
	if err := queryInChunksContext(ctx, tx, ids, nil, `
		SELECT participant_id, person_id FROM person_participants
		WHERE participant_id IN (%s)
		ORDER BY participant_id, person_id`, func(rows *loggedRows) error {
		var participantID, personID int64
		if err := rows.Scan(&participantID, &personID); err != nil {
			return fmt.Errorf("scan participant person binding: %w", err)
		}
		bindings[participantID] = append(bindings[participantID], personID)
		return nil
	}); err != nil {
		return nil, fmt.Errorf("load participant person bindings: %w", err)
	}
	return bindings, nil
}

func personsForMembers(members []int64, bindings map[int64][]int64) []int64 {
	persons := []int64{}
	for _, member := range members {
		persons = append(persons, bindings[member]...)
	}
	slices.Sort(persons)
	return slices.Compact(persons)
}

type participantPersonPair struct {
	participantID, personID int64
}

// rejectedContactMatchPairsTx loads every rejected participant-to-person
// decision. A rejection of any member of a cluster suppresses the whole
// cluster for that person, whichever identifier produced it.
func rejectedContactMatchPairsTx(
	ctx context.Context, tx *loggedTx,
) (map[participantPersonPair]struct{}, error) {
	rows, err := tx.QueryContext(ctx, `SELECT left_id, right_id FROM identity_match_candidates
		WHERE state = ? AND left_kind = ? AND right_kind = ?`,
		IdentityMatchStateRejected, IdentityMatchParticipant, IdentityMatchPerson)
	if err != nil {
		return nil, fmt.Errorf("load rejected participant-to-person matches: %w", err)
	}
	defer func() { _ = rows.Close() }()
	rejected := map[participantPersonPair]struct{}{}
	for rows.Next() {
		var pair participantPersonPair
		if err := rows.Scan(&pair.participantID, &pair.personID); err != nil {
			return nil, fmt.Errorf("scan rejected participant-to-person match: %w", err)
		}
		rejected[pair] = struct{}{}
	}
	return rejected, rows.Err()
}

// contactMatchBlockReasonsTx reports people a person merge would refuse: a
// CardDAV publication or an unresolved CardDAV conflict with local intent.
// It mirrors ensurePersonMergeCardDAVStateTx so the queue shows the same
// verdict the merge would return.
func contactMatchBlockReasonsTx(
	ctx context.Context, tx *loggedTx, personIDs []int64,
) (map[int64]ContactMatchBlockReason, error) {
	ids := slices.Clone(personIDs)
	slices.Sort(ids)
	ids = slices.Compact(ids)
	blocks := map[int64]ContactMatchBlockReason{}
	if err := queryInChunksContext(ctx, tx, ids, nil, `
		SELECT r.person_id FROM carddav_conflicts c
		JOIN carddav_resources r ON r.address_book_id = c.address_book_id AND r.href = c.href
		WHERE c.status = 'unresolved' AND c.local_mutation_intent IS NOT NULL
		  AND r.person_id IN (%s)`, func(rows *loggedRows) error {
		var personID int64
		if err := rows.Scan(&personID); err != nil {
			return fmt.Errorf("scan CardDAV conflict person: %w", err)
		}
		blocks[personID] = ContactMatchBlockedCardDAVConflict
		return nil
	}); err != nil {
		return nil, fmt.Errorf("load contact match CardDAV conflicts: %w", err)
	}
	if err := queryInChunksContext(ctx, tx, ids, nil, `
		SELECT person_id FROM carddav_publications WHERE person_id IN (%s)`,
		func(rows *loggedRows) error {
			var personID int64
			if err := rows.Scan(&personID); err != nil {
				return fmt.Errorf("scan CardDAV publication person: %w", err)
			}
			blocks[personID] = ContactMatchBlockedPublished
			return nil
		}); err != nil {
		return nil, fmt.Errorf("load contact match CardDAV publications: %w", err)
	}
	return blocks, nil
}

// ContactMatchBuildResult summarizes one contact-match refresh.
type ContactMatchBuildResult struct {
	Matches  int `json:"matches"`
	Created  int `json:"created"`
	Existing int `json:"existing"`
	// Retired counts undecided candidates removed because they no longer
	// qualify, for example because their cluster became an owner identity.
	Retired       int `json:"retired"`
	EvidenceAdded int `json:"evidence_added"`
	Bind          int `json:"bind"`
	Merge         int `json:"merge"`
	Ambiguous     int `json:"ambiguous"`
	Blocked       int `json:"blocked"`
	// SharedMailbox counts matches through addresses that look shared.
	SharedMailbox int `json:"shared_mailbox"`
	// AutoMerged counts contact profiles merged into the one archive person
	// that already has their exact email.
	AutoMerged int `json:"auto_merged"`
	// AutoBound counts unbound archive identity clusters linked to the one
	// contact profile with their exact email.
	AutoBound int `json:"auto_bound"`
	// LinkedClosed counts pending candidates accepted because the archive
	// identity already belonged to the contact profile.
	LinkedClosed int `json:"linked_closed"`
	// LeftForReview counts contact-match candidates still waiting for a
	// decision after this refresh.
	LeftForReview int `json:"left_for_review"`
	// DryRun marks a report of what a refresh would decide; nothing was
	// written.
	DryRun bool `json:"dry_run,omitzero"`
	// Actions lists each automatic decision by IDs: merges, binds, and
	// closed linked candidates.
	Actions []ContactMatchAutoAction `json:"actions,omitempty"`
	// CacheState is set by the HTTP endpoint after it refreshes the identity
	// datasets for automatic merges or links; it is omitted when the refresh
	// changed no person.
	CacheState string `json:"cache_state,omitempty" enum:"ready,stale"`
}

// BuildContactMatchCandidatesContext writes one reviewable identity match
// candidate per contact-only profile and matched participant cluster. The
// participant endpoint is the lowest matched cluster member, the basis is
// email when any email matched and phone otherwise, the source is system with
// confidence 1.0 (exact identifiers), and every matching contact point is
// recorded as evidence. Reruns are idempotent: a cluster that already has a
// contact-match candidate for the profile, in any state, gains only new
// evidence.
//
// Exact matches are then decided in code (see planContactMatchAutoTx):
// a pending merge or bind supported by an exact email, between one contact
// profile and one archive identity cluster with nothing blocking it, is
// applied through the ordinary person merge path and recorded as accepted by
// ContactMatchAutoActor. Pending candidates that are already linked are
// closed. Everything else stays in the review queue.
func (s *Store) BuildContactMatchCandidatesContext(
	ctx context.Context,
) (*ContactMatchBuildResult, error) {
	return s.BuildContactMatchCandidatesWithOptionsContext(ctx, ContactMatchBuildOptions{})
}

// BuildContactMatchCandidatesWithOptionsContext is
// BuildContactMatchCandidatesContext with a dry run. Candidates are written
// in one transaction; the automatic resolutions follow in bounded batches,
// each re-validated under the identity lock.
func (s *Store) BuildContactMatchCandidatesWithOptionsContext(
	ctx context.Context, options ContactMatchBuildOptions,
) (*ContactMatchBuildResult, error) {
	if options.DryRun {
		return s.dryRunContactMatchBuildContext(ctx)
	}
	result := &ContactMatchBuildResult{}
	var plan []contactMatchAutoPlan
	err := s.withTxContext(ctx, func(tx *loggedTx) error {
		*result = ContactMatchBuildResult{}
		var err error
		plan, _, err = s.writeContactMatchCandidatesTx(ctx, tx, result)
		return err
	})
	if err != nil {
		return nil, err
	}
	if s.contactMatchAutoBeforeApplyHook != nil {
		s.contactMatchAutoBeforeApplyHook()
	}
	if err := s.applyContactMatchAutoPlanContext(ctx, plan, result); err != nil {
		return nil, err
	}
	err = s.withReadSnapshotContext(ctx, func(tx *loggedTx) error {
		var err error
		result.LeftForReview, err = pendingContactMatchCountTx(ctx, tx)
		return err
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

// writeContactMatchCandidatesTx is the first phase of a refresh, under the
// identity lock: it retires stale candidates, closes linked ones, writes a
// candidate per match, and plans the exact matches to resolve. It returns
// the plan and the IDs of the candidates it created.
func (s *Store) writeContactMatchCandidatesTx(
	ctx context.Context, tx *loggedTx, result *ContactMatchBuildResult,
) ([]contactMatchAutoPlan, map[int64]struct{}, error) {
	if err := s.lockIdentityMutationTxContext(ctx, tx); err != nil {
		return nil, nil, err
	}
	retired, err := s.retireStaleContactMatchCandidatesTx(ctx, tx)
	if err != nil {
		return nil, nil, err
	}
	result.Retired = retired
	closed, err := s.closeLinkedContactMatchCandidatesTx(ctx, tx)
	if err != nil {
		return nil, nil, err
	}
	result.LinkedClosed = len(closed)
	result.Actions = append(result.Actions, closed...)
	matches, err := s.findContactMatchesTx(ctx, tx)
	if err != nil {
		return nil, nil, err
	}
	existing, err := existingContactMatchCandidatesTx(ctx, tx)
	if err != nil {
		return nil, nil, err
	}
	before := make(map[int64]struct{}, len(existing))
	for _, id := range existing {
		before[id] = struct{}{}
	}
	written := make([]writtenContactMatch, 0, len(matches))
	created := map[int64]struct{}{}
	for _, match := range matches {
		candidateID, err := s.writeContactMatchCandidateTx(ctx, tx, match, existing, result)
		if err != nil {
			return nil, nil, err
		}
		if _, existed := before[candidateID]; !existed {
			created[candidateID] = struct{}{}
		}
		written = append(written, writtenContactMatch{match: match, candidateID: candidateID})
	}
	plan, err := s.planContactMatchAutoTx(ctx, tx, written)
	if err != nil {
		return nil, nil, err
	}
	return plan, created, nil
}

func countContactMatchClassification(match ContactMatch, result *ContactMatchBuildResult) {
	result.Matches++
	switch match.Classification {
	case ContactMatchBind:
		result.Bind++
	case ContactMatchMerge:
		result.Merge++
	case ContactMatchAmbiguous:
		result.Ambiguous++
	case ContactMatchSharedMailbox:
		result.SharedMailbox++
	case ContactMatchLinked:
	}
	if match.BlockedReason != nil {
		result.Blocked++
	}
}

func (s *Store) writeContactMatchCandidateTx(
	ctx context.Context, tx *loggedTx, match ContactMatch,
	existing map[participantPersonPair]int64, result *ContactMatchBuildResult,
) (int64, error) {
	countContactMatchClassification(match, result)
	var candidateID int64
	for _, member := range match.ClusterMembers {
		if id, ok := existing[participantPersonPair{
			participantID: member, personID: match.ContactPersonID,
		}]; ok {
			candidateID = id
			break
		}
	}
	if candidateID != 0 {
		result.Existing++
	} else {
		primary := match.Identifiers[0]
		normalized := primary.NormalizedValue
		confidence := 1.0
		sourceRef := ContactMatchSourceRef
		candidate, created, err := s.upsertIdentityMatchCandidateTx(ctx, tx,
			IdentityMatchCandidateInput{
				LeftKind: IdentityMatchParticipant, LeftID: match.ParticipantID,
				RightKind: IdentityMatchPerson, RightID: match.ContactPersonID,
				Basis: primary.Basis, NormalizedValue: &normalized,
				State: IdentityMatchStateCandidate, Confidence: &confidence,
				Source: ProvenanceSystem, SourceRef: &sourceRef,
			},
			IdentityMatchParticipant, match.ParticipantID,
			IdentityMatchPerson, match.ContactPersonID, nil, false)
		if err != nil {
			return 0, fmt.Errorf("write contact match candidate: %w", err)
		}
		candidateID = candidate.ID
		existing[participantPersonPair{
			participantID: match.ParticipantID, personID: match.ContactPersonID,
		}] = candidateID
		if created {
			result.Created++
		} else {
			result.Existing++
		}
	}
	for _, identifier := range match.Identifiers {
		ref := fmt.Sprintf("person_contact_point:%d", identifier.ContactPointID)
		detail := fmt.Sprintf("participant %d %s=%s",
			identifier.ParticipantID, identifier.MatchedField, identifier.MatchedValue)
		_, inserted, err := s.addIdentityMatchEvidenceTx(ctx, tx, candidateID,
			ContactMatchEvidenceKind, IdentityMatchEvidenceInput{
				EvidenceRef: &ref, Detail: &detail, Source: ProvenanceSystem,
			})
		if err != nil {
			return 0, err
		}
		if inserted {
			result.EvidenceAdded++
		}
	}
	return candidateID, nil
}

// existingContactMatchCandidatesTx maps each contact-match candidate's
// participant and person endpoints to its ID.
func existingContactMatchCandidatesTx(
	ctx context.Context, tx *loggedTx,
) (map[participantPersonPair]int64, error) {
	rows, err := tx.QueryContext(ctx, `SELECT id, left_id, right_id
		FROM identity_match_candidates
		WHERE source_ref = ? AND left_kind = ? AND right_kind = ?
		ORDER BY id`,
		ContactMatchSourceRef, IdentityMatchParticipant, IdentityMatchPerson)
	if err != nil {
		return nil, fmt.Errorf("load contact match candidates: %w", err)
	}
	defer func() { _ = rows.Close() }()
	existing := map[participantPersonPair]int64{}
	for rows.Next() {
		var id int64
		var pair participantPersonPair
		if err := rows.Scan(&id, &pair.participantID, &pair.personID); err != nil {
			return nil, fmt.Errorf("scan contact match candidate: %w", err)
		}
		if _, seen := existing[pair]; !seen {
			existing[pair] = id
		}
	}
	return existing, rows.Err()
}

// retireStaleContactMatchCandidatesTx deletes undecided contact-match
// candidates that no longer qualify. Decided rows are the user's record and
// are never removed.
func (s *Store) retireStaleContactMatchCandidatesTx(ctx context.Context, tx *loggedTx) (int, error) {
	rows, err := tx.QueryContext(ctx, `SELECT id, left_id, right_id
		FROM identity_match_candidates
		WHERE source_ref = ? AND left_kind = ? AND right_kind = ? AND state = ?
		ORDER BY id`,
		ContactMatchSourceRef, IdentityMatchParticipant, IdentityMatchPerson,
		IdentityMatchStateCandidate)
	if err != nil {
		return 0, fmt.Errorf("load undecided contact match candidates: %w", err)
	}
	pending := []IdentityMatchCandidate{}
	for rows.Next() {
		var row IdentityMatchCandidate
		if err := rows.Scan(&row.ID, &row.LeftID, &row.RightID); err != nil {
			_ = rows.Close()
			return 0, fmt.Errorf("scan undecided contact match candidate: %w", err)
		}
		row.LeftKind, row.RightKind = IdentityMatchParticipant, IdentityMatchPerson
		pending = append(pending, row)
	}
	if err := rows.Close(); err != nil {
		return 0, fmt.Errorf("close undecided contact match candidates: %w", err)
	}
	if len(pending) == 0 {
		return 0, nil
	}
	edges, err := s.loadLinkEdgesTxContext(ctx, tx)
	if err != nil {
		return 0, err
	}
	adjacency := buildAdjacency(edges)
	retired := 0
	for _, row := range pending {
		component := componentOfAdj(row.LeftID, adjacency)
		members := make([]int64, 0, len(component))
		for id := range component {
			members = append(members, id)
		}
		slices.Sort(members)
		guardErr := s.contactMatchAcceptGuardsTx(ctx, tx, row, members)
		if guardErr == nil {
			continue
		}
		if !isContactMatchRetirement(guardErr) {
			return retired, guardErr
		}
		if _, err := tx.ExecContext(ctx,
			`DELETE FROM identity_match_candidates WHERE id = ? AND state = ?`,
			row.ID, IdentityMatchStateCandidate); err != nil {
			return retired, fmt.Errorf("retire contact match candidate %d: %w", row.ID, err)
		}
		retired++
	}
	return retired, nil
}

// isContactMatchRetirement reports whether an accept guard failure means the
// candidate no longer qualifies, as opposed to an operational error.
func isContactMatchRetirement(err error) bool {
	return errors.Is(err, ErrContactMatchOwnerIdentity) ||
		errors.Is(err, ErrContactMatchStale) ||
		errors.Is(err, ErrContactMatchRejectedInCluster) ||
		errors.Is(err, ErrContactMatchNotAPerson)
}
